### ISSUE TITLE
META: EDA

### ISSUE THREAD

**Issue by jess-goddard** [SimpleLab-Inc/wsb#15]
**Objective**
Markdown report summarizing key exploratory data insights to inform modeling. This issue will track a to-do list of EDA tasks that can be developed in various branches and issues.

**EDA Questions/Exploratory Directions**

_Missingness_
- [x] Existing coverage of spatial labeled data
- [x] Centroid coverage 
- [x] Tabular data: assess missingness for key categories (i.e., population served, system size AKA connection count)
- [x] List of URLs by state to track data sources, [here](https://docs.google.com/spreadsheets/d/1ov0vx0A-qawxLwASHNRUIyXgJXhLjBHIQ4JxdhIyW4o/edit#gid=0) 

_Data Quality_
- [x] Number of "imposter" centroids across datasets (echo, frs, mhp)
- [x] Centroids of low quality (e.g. `fac_collection_method` is state or county centroid). break down by state, system size (?) -> when we don't have labeled boundary or TIGRIS, collection method is really important, we need to characterize how big this group is and where they plot, and how to address them.
- [x] Appropriateness of TIGER boundaries as proxy. Compare join for labeled systems: e.g., city of Davis, and Davis TIGRIS places -> boolean T/F and jacard (less important)

_Coverage relative to SDWIS master list of active, community water systems_
- [x] Summary of existing boundary coverage by system size (using [EPA categories](https://echo.epa.gov/help/drinking-water-dashboard-help))
- [x] Summary of existing boundary coverage by system type (Municipal, etc) / ownership type
- [x] Summary of existing boundary coverage by tribal vs non-tribal (i.e. primacy_type_code is territory?)
- [x] Total US population served by existing boundary date (using SDWIS provided `population_served`)
