### ISSUE TITLE
META: hierarchically estimate PWS centroids

### ISSUE THREAD

**Issue by richpauloo** [SimpleLab-Inc/wsb#2]
We need to estimate centroids for unlabeled data to give an initial starting point for the model (props to @jess-goddard for this tiered idea). 

This issue incorporates downloaders and analysis and itself comprises a meta issue. We assign centroids to PWS based on the following hierarchy ordered by data fidelity. Tier 1 is for labeled data and Tiers 2-3 are for unlabeled data. A downloader is required for for FRS centroids (Tier 2), and a downloader/transformer is needed for geocoded addresses (Tier 3).

**1. compute from water system boundary (as it exits)**
- [x] Transformer for general preprocessing of labeled data (e.g., use `ST CENTROID` on polygons)

**2. TIGRIS places as proxies for municipal systems**

- [x] Downloader for TIGRIS places #4 
- [x] Sandbox EDA to explore connecting TIGRIS places to PWSID names, use regex "[To be determined]" to match TIGRIS places and PWSID names. Explore error associated with applying this approach in states with labeled data. Make recommendations for a transformer operation to extend this to unlabeled data. #5

**3. FRS centroid (e.g. see the Baltimore city water data [here](https://echo.epa.gov/detailed-facility-report?fid=MD0300002&sys=SDWIS))** 

- [x] downloader for FRS centroid #3 
- [x] transformer for FRS data #16 

**4. Geocode administrative address from SDWIS (worst option, b/c admin address can be in a totally different location than system served) in a transformer that incorporates** 

- [x] downloader for SDWIS admin addresses #6
- [ ] transformer that geocodes the data downloaded by the downloader above into lat/lng centroids #7
- [ ] sanity check the appropriateness of geocoded boundaries in the sandbox that estimates error for the geocoding above  #8

If there is another source we can use between 2) and 3) that we find, great.

**FINALLY**:

- [x] Transformer that populates the centroid field and writes to the clean, staging path.

![image](https://user-images.githubusercontent.com/10336683/150875735-786fdd36-32bd-467d-a342-8da08d660870.png)
