### ISSUE TITLE
Repository documentation

### ISSUE THREAD

**Issue by jess-goddard** [SimpleLab-Inc/wsb#81]
Current thinking on repository documentation structure:

- [x] Concise root directory README developer guide with overview of each repository section and LINKS to that sections README (for those below)
- [x] README for data sources #58 @jess-goddard 
- [x] README contributor guide/ overview for downloaders #90 @noorkb @jess-goddard 
- [x] README contributor guide/ overview for transformers #94 @noorkb @jess-goddard 
- [x] README contributor guide/ overview for matching @ryanshepherd 
- [x] README contributor guide/ overview for modeling @richpauloo 
- [x] README contributor guide/ overview for sandbox @richpauloo 
- [x] README contributor guide for contributing to repository @richpauloo @jess-goddard
